import sqlite3

# Conecte ao banco de dados (ou crie um novo)
conn = sqlite3.connect("biblioteca.db")
cursor = conn.cursor()


# Criação da tabela livros
cursor.execute(
    """
CREATE TABLE IF NOT EXISTS livros (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo TEXT NOT NULL,
    estado_do_livro TEXT NOT NULL,
    ano INTEGER,
    data_aquisicao DATE,
    observacao TEXT,
    lido INTEGER,
    editora_id INTEGER,
    FOREIGN KEY(editora_id) REFERENCES editoras(id)
);
"""
)

# Inserir dados na tabela livros
cursor.executemany(
    """
INSERT INTO livros (id, titulo, estado_do_livro, ano, data_aquisicao, observacao, lido, editora_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
""",
    [
        (
            1,
            "The Art of War",
            "Disponível",
            500,
            "2023-01-01",
            "Disponível para empréstimo",
            0,
            1,
        ),
        (
            2,
            "The Science Fiction Hall of Fame",
            "Emprestado",
            1965,
            "2023-01-02",
            "Disponível para empréstimo",
            1,
            2,
        ),
        (
            3,
            "The Best American Series",
            "Disponível",
            2000,
            "2023-01-03",
            "Disponível para empréstimo",
            0,
            3,
        ),
        (
            4,
            "The Norton Anthology of English Literature",
            "Emprestado",
            1962,
            "2023-02-07",
            "Disponível para empréstimo",
            1,
            4,
        ),
        (
            5,
            "The Oxford Book of American Short Stories",
            "Disponível",
            1992,
            "2023-01-05",
            "Disponível para empréstimo",
            0,
            5,
        ),
        (
            6,
            "The Columbia Anthology of Modern Chinese Drama",
            "Emprestado",
            2008,
            "2023-01-06",
            "Disponível para empréstimo",
            1,
            6,
        ),
        (
            7,
            "The Penguin Book of English Short Stories",
            "Disponível",
            2007,
            "2023-01-07",
            "Disponível para empréstimo",
            0,
            7,
        ),
        (
            8,
            "The Vintage Book of Contemporary American Short Stories",
            "Emprestado",
            1994,
            "2023-01-08",
            "Disponível para empréstimo",
            1,
            8,
        ),
        (
            9,
            "The Cambridge History of the Cold War",
            "Disponível",
            2010,
            "2023-01-09",
            "Disponível para empréstimo",
            0,
            9,
        ),
        (
            10,
            "The HarperCollins Book of English Poetry",
            "Emprestado",
            2004,
            "2023-01-10",
            "Disponível para empréstimo",
            1,
            10,
        ),
        (
            11,
            "The Essential Writings of Ralph Waldo Emerson",
            "Disponível",
            2000,
            "2023-01-11",
            "Disponível para empréstimo",
            0,
            1,
        ),
        (
            12,
            "The Bedford Anthology of American Literature",
            "Emprestado",
            2008,
            "2023-01-12",
            "Disponível para empréstimo",
            1,
            2,
        ),
        (
            13,
            "The Penguin Anthology of 20th Century American Poetry",
            "Disponível",
            2011,
            "2023-01-13",
            "Disponível para empréstimo",
            0,
            3,
        ),
        (
            14,
            "The Complete Works of William Shakespeare",
            "Emprestado",
            2003,
            "2023-01-14",
            "Disponível para empréstimo",
            1,
            4,
        ),
        (
            15,
            "The Routledge Companion to Philosophy in Organization Studies",
            "Disponível",
            2013,
            "2023-01-15",
            "Disponível para empréstimo",
            0,
            5,
        ),
        (
            16,
            "The International Handbook of Social Innovation",
            "Emprestado",
            2014,
            "2023-01-16",
            "Disponível para empréstimo",
            1,
            6,
        ),
        (
            17,
            "The Blackwell Companion to Philosophy of Language",
            "Disponível",
            2012,
            "2023-02-14",
            "Disponível para empréstimo",
            0,
            7,
        ),
        (
            18,
            "The Cambridge Companion to American Poets",
            "Emprestado",
            2008,
            "2023-02-09",
            "Disponível para empréstimo",
            1,
            8,
        ),
        (
            19,
            "The Norton Anthology of World Literature",
            "Disponível",
            2012,
            "2023-01-19",
            "Disponível para empréstimo",
            0,
            9,
        ),
        (
            20,
            "The Oxford Handbook of Global Policy",
            "Emprestado",
            2018,
            "2023-02-11",
            "Disponível para empréstimo",
            1,
            10,
        ),
        (
            21,
            "The Handbook of New Media",
            "Disponível",
            2006,
            "2023-02-15",
            "Disponível para empréstimo",
            1,
            1,
        ),
        (
            22,
            "The Oxford Companion to English Literature",
            "Emprestado",
            2000,
            "2023-01-22",
            "Disponível para empréstimo",
            1,
            2,
        ),
        (
            23,
            "The Cambridge Companion to Feminist Literary Theory",
            "Disponível",
            2004,
            "2023-02-21",
            "Disponível para empréstimo",
            1,
            3,
        ),
        (
            24,
            "The Routledge Companion to Management and Organizational History",
            "Emprestado",
            2016,
            "2023-01-24",
            "Disponível para empréstimo",
            1,
            4,
        ),
        (
            25,
            "The Oxford Handbook of Economic Geography",
            "Disponível",
            2000,
            "2023-02-16",
            "Disponível para empréstimo",
            0,
            5,
        ),
        (
            26,
            "The Palgrave Handbook of Global Health Data",
            "Emprestado",
            2018,
            "2023-01-26",
            "Disponível para empréstimo",
            1,
            6,
        ),
        (
            27,
            "The Routledge Handbook of Japanese Politics",
            "Disponível",
            2016,
            "2023-01-27",
            "Disponível para empréstimo",
            0,
            7,
        ),
        (
            28,
            "The Cambridge History of the Modern World",
            "Emprestado",
            2008,
            "2023-01-28",
            "Disponível para empréstimo",
            1,
            8,
        ),
        (
            29,
            "The Oxford Handbook of Political Psychology",
            "Disponível",
            2011,
            "2023-02-20",
            "Disponível para empréstimo",
            0,
            9,
        ),
        (
            30,
            "The Blackwell Companion to the Bible and Culture",
            "Emprestado",
            2006,
            "2023-01-30",
            "Disponível para empréstimo",
            1,
            10,
        ),
        (
            31,
            "The Cambridge Companion to American Travel Writing",
            "Disponível",
            2008,
            "2023-02-13",
            "Disponível para empréstimo",
            1,
            1,
        ),
        (
            32,
            "The Routledge Handbook of Peacebuilding",
            "Emprestado",
            2013,
            "2023-02-24",
            "Disponível para empréstimo",
            0,
            2,
        ),
        (
            33,
            "The Oxford Handbook of Clinical Medicine",
            "Disponível",
            2014,
            "2023-02-02",
            "Disponível para empréstimo",
            0,
            3,
        ),
        (
            34,
            "The Cambridge History of Latin America",
            "Emprestado",
            2006,
            "2023-02-03",
            "Disponível para empréstimo",
            1,
            4,
        ),
        (
            35,
            "The Routledge Companion to Literature and Psychoanalysis",
            "Disponível",
            2017,
            "2023-02-10",
            "Disponível para empréstimo",
            0,
            5,
        ),
        (
            36,
            "The Cambridge Handbook of Language and Social Interaction",
            "Emprestado",
            2011,
            "2023-02-23",
            "Disponível para empréstimo",
            1,
            6,
        ),
        (
            37,
            "The Penguin Historical Atlas of Ancient Rome",
            "Disponível",
            1998,
            "2023-02-06",
            "Disponível para empréstimo",
            0,
            7,
        ),
        (
            38,
            "The Norton Anthology of English Literature",
            "Emprestado",
            1962,
            "2023-02-07",
            "Disponível para empréstimo",
            1,
            8,
        ),
        (
            39,
            "The Oxford Companion to American Literature",
            "Disponível",
            2001,
            "2023-02-08",
            "Disponível para empréstimo",
            0,
            9,
        ),
        (
            40,
            "The Cambridge Companion to American Poets",
            "Emprestado",
            2008,
            "2023-02-09",
            "Disponível para empréstimo",
            1,
            10,
        ),
        (
            41,
            "The Routledge Companion to Literature and Psychoanalysis",
            "Disponível",
            2017,
            "2023-02-10",
            "Disponível para empréstimo",
            0,
            1,
        ),
        (
            42,
            "The Oxford Handbook of Global Policy",
            "Emprestado",
            2018,
            "2023-02-11",
            "Disponível para empréstimo",
            1,
            2,
        ),
        (
            43,
            "The Cambridge History of Modern European Thought",
            "Disponível",
            2011,
            "2023-02-12",
            "Disponível para empréstimo",
            0,
            3,
        ),
        (
            44,
            "The Cambridge Companion to American Travel Writing",
            "Emprestado",
            2008,
            "2023-02-13",
            "Disponível para empréstimo",
            1,
            4,
        ),
        (
            45,
            "The Blackwell Companion to Philosophy of Language",
            "Disponível",
            2012,
            "2023-02-14",
            "Disponível para empréstimo",
            0,
            5,
        ),
        (
            46,
            "The Handbook of New Media",
            "Emprestado",
            2006,
            "2023-02-15",
            "Disponível para empréstimo",
            1,
            6,
        ),
        (
            47,
            "The Oxford Handbook of Economic Geography",
            "Disponível",
            2000,
            "2023-02-16",
            "Disponível para empréstimo",
            0,
            7,
        ),
        (
            48,
            "The Cambridge Companion to the History of the Book",
            "Emprestado",
            2015,
            "2023-02-17",
            "Disponível para empréstimo",
            1,
            8,
        ),
        (
            49,
            "The Routledge Companion to American Literature",
            "Disponível",
            2020,
            "2023-02-18",
            "Disponível para empréstimo",
            0,
            9,
        ),
        (
            50,
            "The Cambridge Companion to the Philosophy of Language",
            "Emprestado",
            2004,
            "2023-02-19",
            "Disponível para empréstimo",
            1,
            10,
        ),
        (
            51,
            "The Oxford Handbook of Political Psychology",
            "Disponível",
            2011,
            "2023-02-20",
            "Disponível para empréstimo",
            0,
            1,
        ),
        (
            52,
            "The Cambridge Companion to Feminist Literary Theory",
            "Emprestado",
            2004,
            "2023-02-21",
            "Disponível para empréstimo",
            1,
            2,
        ),
        (
            53,
            "The Routledge Handbook of Peacebuilding",
            "Disponível",
            2013,
            "2023-02-24",
            "Disponível para empréstimo",
            0,
            3,
        ),
        (
            54,
            "The Cambridge Handbook of Language and Social Interaction",
            "Emprestado",
            2011,
            "2023-02-23",
            "Disponível para empréstimo",
            1,
            4,
        ),
        (
            55,
            "The Routledge Handbook of Peacebuilding",
            "Disponível",
            2013,
            "2023-02-24",
            "Disponível para empréstimo",
            0,
            5,
        ),
        (
            56,
            "The Oxford Handbook of Social and Political Trust",
            "Emprestado",
            2016,
            "2023-02-25",
            "Disponível para empréstimo",
            1,
            6,
        ),
    ],
)

# Criação da tabela autores
cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS autores (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL
    );
    """
)

# Inserção de dados na tabela autores
cursor.executemany(
    """
    INSERT INTO autores (nome) VALUES (?)
    """,
    [
        ("Sun Tzu",),
        ("Robert Silverberg",),
        ("Best American Series Editor",),
        ("Stephen Greenblatt",),
        ("Joyce Carol Oates",),
        ("Xiaomei Chen",),
        ("Christopher Dolley",),
        ("Tobias Wolff",),
        ("Melvyn P. Leffler",),
        ("Sukrita Paul Kumar",),
        ("Ralph Waldo Emerson",),
        ("Susan Belasco",),
        ("Rita Dove",),
        ("William Shakespeare",),
        ("Raza Mir",),
        ("Frank Moulaert",),
        ("Bob Hale",),
        ("Mark Richardson",),
        ("Martin Puchner",),
        ("Michael Cox",),
        ("Leah A. Lievrouw",),
        ("Dinah Birch",),
        ("Ellen Rooney",),
        ("Patricia Genoe McLaren",),
        ("Gordon L. Clark",),
        ("Núria Homedes",),
        ("Alisa Gaunder",),
        ("David Armitage",),
        ("David O. Sears",),
        ("John F. A. Sawyer",),
        ("Alfred Bendixen",),
        ("Roger Mac Ginty",),
        ("Murray Longmore",),
        ("Leslie Bethell",),
        ("Laura Marcus",),
        ("Jack Sidnell",),
        ("Chris Scarre",),
        ("M. H. Abrams",),
        ("James D. Hart",),
        ("Robert Von Hallberg",),
        ("Jean-Michel Rabaté",),
        ("Helga Nowotny",),
        ("Warren Breckman",),
        ("James Duncan",),
        ("David Schalkwyk",),
        ("Peter Lamarque",),
    ],
)


# Criação da tabela editoras
cursor.execute(
    """
CREATE TABLE IF NOT EXISTS editoras (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);
"""
)

# Inserção de dados na tabela editoras
cursor.executemany(
    """
INSERT INTO editoras (id, nome) VALUES (?, ?)
""",
    [
        (1, "Penguin Random House"),
        (2, "HarperCollins"),
        (3, "Simon & Schuster"),
        (4, "Hachette Livre"),
        (5, "Macmillan Publishers"),
        (6, "Scholastic"),
        (7, "Bloomsbury"),
        (8, "Oxford University Press"),
        (9, "Wiley"),
        (10, "Pearson"),
    ],
)


# Criação da tabela livros_autores (tabela de associação)
cursor.execute(
    """
CREATE TABLE IF NOT EXISTS livros_autores (
    livro_id INTEGER,
    autor_id INTEGER,
    PRIMARY KEY (livro_id, autor_id),
    FOREIGN KEY(livro_id) REFERENCES livros(id),
    FOREIGN KEY(autor_id) REFERENCES autores(id)
);
"""
)

# Inserção de dados na tabela livrs_autores
cursor.executemany(
    """
    INSERT INTO livros_autores (livro_id, autor_id) VALUES (?, ?)
    """,
    [
        (1, 1),
        (47, 1),
        (53, 1),
        (2, 2),
        (47, 2),
        (54, 2),
        (3, 3),
        (48, 3),
        (55, 3),
        (4, 4),
        (48, 4),
        (56, 4),
        (5, 5),
        (49, 5),
        (6, 6),
        (49, 6),
        (7, 7),
        (50, 7),
        (8, 8),
        (50, 8),
        (9, 9),
        (51, 9),
        (10, 10),
        (51, 10),
        (11, 11),
        (52, 11),
        (12, 12),
        (52, 12),
        (13, 13),
        (53, 13),
        (14, 14),
        (53, 14),
        (15, 15),
        (54, 15),
        (16, 16),
        (54, 16),
        (17, 17),
        (55, 17),
        (18, 18),
        (55, 18),
        (19, 19),
        (56, 19),
        (20, 20),
        (56, 20),
        (21, 21),
        (47, 21),
        (22, 22),
        (48, 22),
        (23, 23),
        (49, 23),
        (24, 24),
        (50, 24),
        (25, 25),
        (51, 25),
        (26, 26),
        (52, 26),
        (27, 27),
        (53, 27),
        (28, 28),
        (54, 28),
        (29, 29),
        (55, 29),
        (30, 30),
        (56, 30),
        (31, 31),
        (47, 31),
        (32, 32),
        (48, 32),
        (33, 33),
        (49, 33),
        (34, 34),
        (50, 34),
        (35, 35),
        (51, 35),
        (36, 36),
        (52, 36),
        (37, 37),
        (53, 37),
        (38, 38),
        (54, 38),
        (39, 39),
        (55, 39),
        (40, 40),
        (56, 40),
        (41, 41),
        (47, 41),
        (42, 42),
        (48, 42),
        (43, 43),
        (49, 43),
        (44, 44),
        (50, 44),
        (45, 45),
        (51, 45),
        (46, 46),
        (52, 46),
    ],
)

# Confirma as transações
conn.commit()

# Fecha a conexão
conn.close()

print("Banco de dados criado e populado com sucesso!")
