# Generated by Django 5.1 on 2024-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_alter_movimentacao_tipo_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='saldo_antes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='saldo_apos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
