# Generated by Django 5.1 on 2024-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_movimentacao_saldo_antes_movimentacao_saldo_apos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='saldo_media',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
