# Generated by Django 5.1 on 2024-09-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Iniciado'), (3, 'Concluído'), (4, 'Excluído')], default=1, verbose_name='Status')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1, verbose_name='Prioridade')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('progresso_conclusao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Progresso de Conclusão')),
                ('dataInicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('dataFim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('dataLimite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
