# Generated by Django 5.0.6 on 2024-09-02 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataFim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataLimite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='progresso_conclusao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Progresso de Conclusão'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
