# Generated by Django 5.1 on 2024-08-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.IntegerField(unique=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_conta', models.IntegerField(choices=[(1, 'Conta Corrente'), (2, 'Conta Poupança')])),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
