# Generated by Django 5.1 on 2024-08-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='limite_especial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
